variables:
  PHX_IMAGE_SUFFIX: ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}
  PHX_IMAGE_COMMIT: ${PHX_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}
  PHX_IMAGE_CWD: /srv/back-studio

stages:
  - build
  - deploy

include:
  - local: "/.gitlab/ci/global.yml"
  - local: "/.gitlab/ci/build.yml"
  - local: "/.gitlab/ci/deploy.yml"
