// COMMONS
export const SET_POSTED = "SET_POSTED";
export const SET_ERROR_SPECIAL = "SET_ERROR_SPECIAL";
export const SET_ERROR_POSTING = "SET_ERROR_POSTING";
export const CONTENT_LOADED = "CONTENT_LOADED";
export const CLEAN_CONTENT_STATE = "CLEAN_CONTENT_STATE";
export const SET_ARTICLE_ID = "SET_ARTICLE_ID";

// AUTH
export const SET_MAIL = "SET_MAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_ERROR_AUTH = "SET_ERROR_AUTH";
export const CLEAN_AUTH_STATE = "CLEAN_AUTH_STATE";

// CONTENT LIST
export const SET_CONTENTS_LIST = "SET_CONTENT_LIST";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_IS_OPEN_DUPLICATE_MODAL = "SET_IS_OPEN_DUPLICATE_MODAL";

// ACTION BAR
export const SET_UPDATED_AT = "SET_UPDATED_AT";
export const SET_PUBLISHED = "SET_PUBLISHED";
export const SET_PROGRAMMED = "SET_PROGRAMMED";
export const SET_PUBLISH_SCHEDULE_FAILED = "SET_PUBLISH_SCHEDULE_FAILED";
export const SET_PUBLISH_SCHEDULE_FAIL_DATA = "SET_PUBLISH_SCHEDULE_FAIL_DATA";
export const SET_IS_OPEN_PUBLISH_MODAL = "SET_IS_OPEN_PUBLISH_MODAL";
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL";
export const SET_IS_OPEN_ARCHIVE_MODAL = "SET_IS_OPEN_ARCHIVE_MODAL";
export const SET_A_MODULE_OPEN = "SET_A_MODULE_OPEN";
export const SHOW_HIDE_MODAL = "SHOW_HIDE_MODAL";
export const SET_IS_OPEN_SCHEDULE_MODAL = "SET_IS_OPEN_SCHEDULE_MODAL";
export const SET_IS_SCHEDULED = "SET_IS_SCHEDULED";
export const SET_A_MODULE_IS_OPEN = "SET_A_MODULE_IS_OPEN";

// MAIN IFORMATION
export const ADD_SLUG = "ADD_SLUG";
export const ADD_TITLE = "ADD_TITLE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
export const SET_ERROR_TITLE = "SET_ERROR_TITLE";
export const SET_ERROR_SLUG = "SET_ERROR_SLUG";
export const SET_STATUS = "SET_STATUS";
export const SET_MODIFIED = "SET_MODIFIED";
export const ADD_LANG = "ADD_LANG";
export const SET_COLOR_STYLE = "SET_COLOR_STYLE";
export const SET_CAPTION = "SET_CAPTION";
export const SET_USERS = "SET_USERS";
export const SET_AUTHORS = "SET_AUTHORS";
export const SET_TAGS = "SET_TAGS";
export const SET_TAGS_LIST = "SET_TAGS_LIST";
export const SET_NEW_TAG = "SET_NEW_TAG";

// MANIFESTO
export const SET_IS_MANIFESTO = "IS_MANIFESTO";
export const SET_MANIFESTO_LANG = "SET_MANIFESTO_LANG";
export const SET_MANIFESTO_ID = "SET_MANIFESTO_ID";
export const SET_MANIFESTO_STATUS = "SET_MANIFESTO_STATUS";

// SEO
export const ADD_SEO_TITLE = "ADD_SEO_TITLE";
export const ADD_SEO_DESCRIPTION = "ADD_SEO_DESCRIPTION";

// HOME AND NAVIGATION
export const SET_READING_TIME = "SET_READING_TIME";
export const ADD_HOME_TITLE = "ADD_HOME_TITLE";
export const SET_HOME_IMAGE_UUID = "SET_HOME_IMAGE_UUID";
export const SET_HOME_IMAGE_ALT = "SET_HOME_IMAGE_ALT";
export const SET_NAV_IMAGE_UUID = "SET_NAV_IMAGE_UUID";
export const SET_NAV_IMAGE_ALT = "SET_NAV_IMAGE_ALT";

// MODULES
export const SET_MODULE_LIST = "SET_MODULE_LIST";
export const SET_NEW_MODULE = "SET_NEW_MODULE";
export const CLOSE_MODULE = "CLOSE_MODULE";
export const SET_VALUE_TEXTMODULE = "SET_VALUE_TEXTMODULE";
export const SHOW_CLOSE_MODAL = "SHOW_CLOSE_MODAL";
export const SET_MODULE_POSTED = "SET_MODULE_POSTED";
export const SET_IMAGE_UUID = "SET_IMAGE_UUID";
export const SET_ALT_IMAGE = "SET_ALT_IMAGE";
export const SET_IS_VISIBLE = "SET_IS_VISIBLE";
export const SET_IS_CHANGED = "SET_IS_CHANGED";
export const EDIT_MODULES_LIST = "EDIT_MODULES_LIST";

export const SET_OPINION_QUESTION = "SET_OPINION_QUESTION";
export const SET_OPINION_SHOW_PERCENT = "SET_OPINION_SHOW_PERCENT ";
export const SET_OPINION_SHOW_RESPONSE = "SET_OPINION_SHOW_RESPONSE ";
export const SET_OPINION_SHOW_RIGHT_ANSWER = "SET_OPINION_SHOW_RIGHT_ANSWER";
export const SET_OPINION_EXPLAIN = "SET_OPINION_EXPLAIN ";
export const SET_OPINION_RIGHT_ANSWER = "SET_OPINION_RIGHT_ANSWER";
export const SET_OPINION_TEXT_ANSWER = "SET_OPINION_TEXT_ANSWER";
export const CREATE_OPINION_NEW_ANSWER = "CREATE_OPINION_NEW_ANSWER";
export const DELETE_OPINION_ANSWER = "DELETE_OPINION_ANSWER";

export const SET_CTA_URL = "SET_CTA_URL";
export const SET_CTA_INTRO = "SET_CTA_INTRO";
export const SET_CTA_LABEL = "SET_CTA_LABEL";
export const SET_CTA_DESCRIPTION = "SET_CTA_DESCRIPTION";
export const SET_CTA_IS_NEWTAB = "SET_CTA_IS_NEWTAB";

// USER PANEL

export const SET_POSITION = "SET_POSITION";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_DISPLAYED_NAME = "SET_DISPLAYED_NAME";
export const SET_QUOTE = "SET_QUOTE";
export const SET_EMAIL = "SET_EMAIL";
export const SET_GENDER = "SET_GENDER";
export const SET_PICTURE = "SET_PICTURE";
export const SET_LOCALE = "SET_LOCALE";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_IS_CHANGED = "SET_USER_IS_CHANGED";
export const CLEAN_USER = "CLEAN_USER";
