// COMMONS
export const SET_POSTED = "SET_POSTED";
export const SET_ERROR_SPECIAL = "SET_ERROR_SPECIAL";
export const SET_ERROR_POSTING = "SET_ERROR_POSTING";
export const CONTENT_LOADED = "CONTENT_LOADED";
export const CLEAN_CONTENT_STATE = "CLEAN_CONTENT_STATE";
export const SET_IS_EDITING = "SET_IS_EDITING";
export const SET_ARTICLE_ID = "SET_ARTICLE_ID";

// AUTH
export const SET_MAIL = "SET_MAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_ERROR_AUTH = "SET_ERROR_AUTH";

// CONTENT LIST
export const SET_CONTENTS_LIST = "SET_CONTENT_LIST";
export const SET_PAGINATION = "SET_PAGINATION";

// ACTION BAR
export const SET_UPDATED_AT = "SET_UPDATED_AT";
export const SET_PUBLISHED = "SET_PUBLISHED";
export const SET_PROGRAMMED = "SET_PROGRAMMED";

// HOMESCREEN
export const ADD_SLUG = "ADD_SLUG";
export const ADD_TITLE = "ADD_TITLE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
export const SET_ERROR_TITLE = "SET_ERROR_TITLE";
export const SET_ERROR_SLUG = "SET_ERROR_SLUG";

// SEO
export const ADD_SEO_TITLE = "ADD_SEO_TITLE";
export const ADD_SEO_DESCRIPTION = "ADD_SEO_DESCRIPTION";

// Module Creator

export const SET_MODULE_LIST = "SET_MODULE_LIST";
export const SET_NEW_MODULE = "SET_NEW_MODULE";
export const CLOSE_MODULE = "CLOSE_MODULE";
export const SET_VALUE_TEXTMODULE = "SET_VALUE_TEXTMODULE";
export const SHOW_CLOSE_MODAL = "SHOW_CLOSE_MODAL";
export const SET_MODULE_POSTED = "SET_MODULE_POSTED";
